USE PapyrusNicolas;

--insert data set in the supplier table
INSERT INTO Fournisseurs(NOM_FOURNISSEUR, NUMERO_RUE_FOURNISSEUR, RUE_FOURNISSEUR, CODE_POSTAL_FOURNISSEUR, VILLE_FOURNISSEUR, CONTACT_FOURNISSEUR, SATISFACTION_FOURNISSEUR) VALUES();

-- insert data set in the clients table
INSERT INTO Clients(NOM_CLIENT, VILLE_CLIENT, CODE_POSTAL_CLIENT,  NUMERO_COMMANDE) VALUES('e-leclerc', 'Saint Etienne les Remiremont', 88200, 'St Etienne les Remiremont');
INSERT INTO Clients(NOM_CLIENT, NUMERO_RUE_CLIENT, RUE_CLIENT, VILLE_CLIENT, CODE_POSTAL_CLIENT,  NUMERO_COMMANDE) VALUES('Intermarché', 3, 'rue de la parelle', 'Rupt sur Moselle', 88360);
INSERT INTO Clients(NOM_CLIENT, NUMERO_RUE_CLIENT, RUE_CLIENT, VILLE_CLIENT, CODE_POSTAL_CLIENT,  NUMERO_COMMANDE) VALUES('Cora', 26, 'route de Bussang', 'Remiremont', 88200);
INSERT INTO Clients(NOM_CLIENT, NUMERO_RUE_CLIENT, RUE_CLIENT, VILLE_CLIENT, CODE_POSTAL_CLIENT,  NUMERO_COMMANDE) VALUES('Intermarché', 6, 'rang de Veseaux route Saint Anne', 'Saint Nabord', 88200);