CREATE DATABASE IF NOT EXIST Editeur

CREATE TABLE IF NOT EXIST Bookshops
(
BookshopName VARCHAR(50) PRIMARY KEY NOT NULL, 
Bookshop_adress VARCHAR(50) NOT NULL,
)

CREATE TABLE IF NOT EXIST Authors
(
Author_firstname VARCHAR(50) PRIMARY KEY NOT NULL,
Author_lastname VARCHAR(50) PRIMARY KEY NOT NULL,
Author_pseudo VARCHAR(50) NULL,
)

CREATE TABLE IF NOT EXIST Editions
(
Edition_number SMALLINT PRIMARY KEY NOT NULL,
Edition_date DATE NOT NULL,
Edition_copyNumber SMALLINT NOT NULL,
)

CREATE TABLE IF NOT EXIST Books
(
Book_isbnNumber INT PRIMARY KEY NOT NULL,
Book_title VARCHAR(50) NOT NULL,
Book_price DECIMAL(4,2) NOT NULL,
Book_award VARCHAR(50) NULL,
Author_firstname VARCHAR(50) FOREIGN KEY NOT NULL,
Author_lastname VARCHAR(50) FOREIGN KEY NOT NULL,
Edition_number SMALLINT FOREIGN KEY NOT NULL,
)

CREATE TABLE IF NOT EXIST Orders
(
Order_number VARCHAR(15) PRIMARY KEY NOT NULL,
Order_quantity TINYINT NOT NULL,
Order_date DATE NOT NULL,
Bookshop_name VARCHAR(50) FOREIGN KEY NOT NULL,
Book_isbnNumber INT FOREIGN KEY NOT NULL,
)