USE PapyrusNicolas;

--insert data set in the supplier table
INSERT INTO Fournisseurs(NOM_FOURNISSEUR, NUMERO_RUE_FOURNISSEUR, RUE_FOURNISSEUR, CODE_POSTAL_FOURNISSEUR, VILLE_FOURNISSEUR, CONTACT_FOURNISSEUR, SATISFACTION_FOURNISSEUR) VALUES('Grosbrigan', 20, 'rue du papier', 99200, 'Papercity', 'Georges', 8);
INSERT INTO Fournisseurs(NOM_FOURNISSEUR, NUMERO_RUE_FOURNISSEUR, RUE_FOURNISSEUR, CODE_POSTAL_FOURNISSEUR, VILLE_FOURNISSEUR, CONTACT_FOURNISSEUR, SATISFACTION_FOURNISSEUR) VALUES('Eclipse', 21, 'rue sans soleil', 54310, 'nightcity', 'Stephanie', 4);
INSERT INTO Fournisseurs(NOM_FOURNISSEUR, NUMERO_RUE_FOURNISSEUR, RUE_FOURNISSEUR, CODE_POSTAL_FOURNISSEUR, VILLE_FOURNISSEUR, CONTACT_FOURNISSEUR, SATISFACTION_FOURNISSEUR) VALUES('Medicis', 51, 'rue medoc', 12031, 'laboratoirecity', 'hyppolite', 7);
INSERT INTO Fournisseurs(NOM_FOURNISSEUR, NUMERO_RUE_FOURNISSEUR, RUE_FOURNISSEUR, CODE_POSTAL_FOURNISSEUR, VILLE_FOURNISSEUR, CONTACT_FOURNISSEUR, SATISFACTION_FOURNISSEUR) VALUES('Discobol', 40, 'rue de la decouverte', 75201, 'curieuxcity', 'Tom', 9);
INSERT INTO Fournisseurs(NOM_FOURNISSEUR, NUMERO_RUE_FOURNISSEUR, RUE_FOURNISSEUR, CODE_POSTAL_FOURNISSEUR, VILLE_FOURNISSEUR, CONTACT_FOURNISSEUR, SATISFACTION_FOURNISSEUR) VALUES('Depanpap', 62,  'rue du bois', 23540, 'Forestcity', 'Emilie', 7);
INSERT INTO Fournisseurs(NOM_FOURNISSEUR, NUMERO_RUE_FOURNISSEUR, RUE_FOURNISSEUR, CODE_POSTAL_FOURNISSEUR, VILLE_FOURNISSEUR, CONTACT_FOURNISSEUR, SATISFACTION_FOURNISSEUR) VALUES('HurryTape', 5, 'rue du ruban', 54300, 'Tapecity', 'Aurelien', 6);

-- insert data set in the clients table
INSERT INTO Clients(NOM_CLIENT,  RUE_CLIENT, VILLE_CLIENT, CODE_POSTAL_CLIENT) VALUES('e-leclerc', 'ZA Chaume', 'Saint Etienne les Remiremont', 88200);
INSERT INTO Clients(NOM_CLIENT, NUMERO_RUE_CLIENT, RUE_CLIENT, VILLE_CLIENT, CODE_POSTAL_CLIENT) VALUES('Intermarché', 3, 'rue de la parelle', 'Rupt sur Moselle', 88360);
INSERT INTO Clients(NOM_CLIENT, NUMERO_RUE_CLIENT, RUE_CLIENT, VILLE_CLIENT, CODE_POSTAL_CLIENT) VALUES('Cora', 26, 'route de Bussang', 'Remiremont', 88200);
INSERT INTO Clients(NOM_CLIENT, NUMERO_RUE_CLIENT, RUE_CLIENT, VILLE_CLIENT, CODE_POSTAL_CLIENT) VALUES('Intermarché', 6, 'rang de Veseaux route Saint Anne', 'Saint Nabord', 88200);

-- insert data set in the products table
INSERT INTO Produits(CODE_ARTICLE, LIBELLE_ARTICLE, STOCK_ALERTE, STOCK_PHYSIQUE, QUANTITE_ANNUELLE, UNITE_MESURE) VALUES('I100', 'Papier 1 ex continu', 100, 557, 3500, 'B100');
INSERT INTO Produits(CODE_ARTICLE, LIBELLE_ARTICLE, STOCK_ALERTE, STOCK_PHYSIQUE, QUANTITE_ANNUELLE, UNITE_MESURE) VALUES('I101', 'Papier 2 ex continu', 100, 350, 2600, 'B100');
INSERT INTO Produits(CODE_ARTICLE, LIBELLE_ARTICLE, STOCK_ALERTE, STOCK_PHYSIQUE, QUANTITE_ANNUELLE, UNITE_MESURE) VALUES('I102', 'Papier 3 ex continu', 100, 230, 1500, 'B100');
INSERT INTO Produits(CODE_ARTICLE, LIBELLE_ARTICLE, STOCK_ALERTE, STOCK_PHYSIQUE, QUANTITE_ANNUELLE, UNITE_MESURE) VALUES('I103', 'Papier 4 ex continu', 100, 700, 4200, 'B100');
INSERT INTO Produits(CODE_ARTICLE, LIBELLE_ARTICLE, STOCK_ALERTE, STOCK_PHYSIQUE, QUANTITE_ANNUELLE, UNITE_MESURE) VALUES('R300', 'Pré imprimé commande', 100, 150, 5000, 'B100');
INSERT INTO Produits(CODE_ARTICLE, LIBELLE_ARTICLE, STOCK_ALERTE, STOCK_PHYSIQUE, QUANTITE_ANNUELLE, UNITE_MESURE) VALUES('R301', 'Pré imprimé facture', 100, 225, 4600, 'B100');
INSERT INTO Produits(CODE_ARTICLE, LIBELLE_ARTICLE, STOCK_ALERTE, STOCK_PHYSIQUE, QUANTITE_ANNUELLE, UNITE_MESURE) VALUES('R302', 'Pré imprimé bulletin paye', 100, 320, 5100, 'B100');

-- insert data set in the product_to-sell table
INSERT INTO Produits_a_Vendre(CODE_ARTICLE, NUMERO_FOURNISSEUR, DELIVRER, QUANTITE, PRIX) VALUES('I102', 3, 120, 500, 230.5);
INSERT INTO Produits_a_Vendre(CODE_ARTICLE, NUMERO_FOURNISSEUR, DELIVRER, QUANTITE, PRIX) VALUES('R302', 1, 75, 300, 320.23);
INSERT INTO Produits_a_Vendre(CODE_ARTICLE, NUMERO_FOURNISSEUR, DELIVRER, QUANTITE, PRIX) VALUES('I103', 2, 100, 325, 275.32);
INSERT INTO Produits_a_Vendre(CODE_ARTICLE, NUMERO_FOURNISSEUR, DELIVRER, QUANTITE, PRIX) VALUES('R301', 1, 175, 620, 180.48);

-- insert date set in the order
INSERT INTO Commandes(OBSERVATION_COMMANDE, DATE_COMMANDE, NUMERO_CLIENT) VALUES('commande urgente', '2020-11-03', 2);
INSERT INTO Commandes(OBSERVATION_COMMANDE, DATE_COMMANDE, NUMERO_CLIENT) VALUES('commande normal', '2020-11-16', 1);
INSERT INTO Commandes(OBSERVATION_COMMANDE, DATE_COMMANDE, NUMERO_CLIENT) VALUES('commande urgente', '2020-11-03', 3);

-- insert data set in the order list
INSERT INTO Liste_Commandes(CODE_ARTICLE, NUMERO_COMMANDE, NUMERO_LIVRAISON, QUANTITE_COMMANDER, PRIX_UNITAIRE, QUANTITE_DELIVRER, DERNIERE_LIVRAISON) VALUES('I102', 1, 136540, 120, 0.46, 100, '2020-11-06');
INSERT INTO Liste_Commandes(CODE_ARTICLE, NUMERO_COMMANDE, NUMERO_LIVRAISON, QUANTITE_COMMANDER, PRIX_UNITAIRE, QUANTITE_DELIVRER, DERNIERE_LIVRAISON) VALUES('R302', 3, 136541, 75, 0.3, 75, '2020-11-21');
INSERT INTO Liste_Commandes(CODE_ARTICLE, NUMERO_COMMANDE, NUMERO_LIVRAISON, QUANTITE_COMMANDER, PRIX_UNITAIRE, QUANTITE_DELIVRER, DERNIERE_LIVRAISON) VALUES('I103', 2, 136542, 150, 0.85, 150, '2020-11-16');
