USE master;
DROP DATABASE IF EXISTS TrouveUnEmploiNicolas;
CREATE DATABASE TrouveUnEmploiNicolas;
USE TrouveUnEmploiNicolas;

DROP TABLE IF EXISTS DIPLOMESDUDEMANDEURDEMPLOI ;
DROP TABLE IF EXISTS DIPLOMES;
DROP TABLE IF EXISTS DEMANDEURDEMPLOIS;

CREATE TABLE DEMANDEURDEMPLOIS
(
    NumSecuriteSocial BIGINT NOT NULL PRIMARY KEY,
    Nom VARCHAR(50) NOT NULL, 
    Prenom VARCHAR(50) NOT NULL, 
    DateDinscription DATETIME NULL,
);

CREATE TABLE DIPLOMES
(
    Id INT NOT NULL PRIMARY KEY, 
    Intitule NVARCHAR(50) NOT NULL
);

CREATE TABLE DIPLOMESDUDEMANDEURDEMPLOI
(
    IdDemandeurDEmploi BIGINT NOT NULL FOREIGN KEY REFERENCES DEMANDEURDEMPLOIS(NumSecuriteSocial), 
    IdDuDiplomes INT NOT NULL FOREIGN KEY REFERENCES DIPLOMES(Id), 
    AnneeDeValidation DATETIME NOT NULL 
);
