DROP DATABASE IF EXISTS pocession_vehicule;
CREATE DATABASE pocession_vehicule;
USE pocession_vehicule;
CREATE TABLE Personne
(
id_Personne INT UNSIGNED AUTO_INCREMENT	NOT NULL PRIMARY KEY,
Nom VARCHAR(50) NOT NULL,
Prenom VARCHAR(50) NOT NULL,
N°_Rue TINYINT UNSIGNED NULL,
Rue VARCHAR(128) NOT NULL,
CP MEDIUMINT UNSIGNED NOT NULL,
Ville VARCHAR(50) NOT NULL
);
CREATE TABLE Vehicule
(
immatriculation CHAR(9) NOT NULL PRIMARY KEY,
Marque VARCHAR(30) NOT NULL,
Kilometrage INT NOT NULL,
Date_mise_en_service DATE NOT NULL,
id_Personne INT UNSIGNED AUTO_INCREMENT	NOT NULL,
CONSTRAINT FK_Personne FOREIGN KEY(id_Personne) REFERENCES Personne(id_Personne)
);
