DROP DATABASE IF EXISTS vendeur;
CREATE DATABASE vendeur;
USE vendeur;
CREATE TABLE Magasins
(
codeM CHAR(20) NOT NULL PRIMARY KEY, -- format du code magasin ?
nomM VARCHAR(20) NOT NULL
);
CREATE TABLE Rayons
(
nomR CHAR(20) NOT NULL PRIMARY KEY
);
CREATE TABLE Articles
(
codeA CHAR(20) NOT NULL PRIMARY KEY, -- format du code article ?
nomA VARCHAR(128) NOT NULL,
typeA VARCHAR(128) NOT NULL
);
CREATE TABLE Ventes
(
num_vente INT UNSIGNED NOT NULL PRIMARY KEY,
nomR CHAR(20) NOT NULL,
codeM CHAR(20) NOT NULL,
codeA CHAR(20) NULL,
dateCommande DATETIME NOT NULL,
quantites INT UNSIGNED NOT NULL,
CONSTRAINT FK_nomR FOREIGN KEY(nomR) REFERENCES Rayons(nomR),
CONSTRAINT FK_codeM FOREIGN KEY(codeM) REFERENCES Magasins(codeM),
CONSTRAINT FK_codeA FOREIGN KEY(codeA) REFERENCES Articles(codeA)
);